version: "3.8"
services:
  app:
    build:
      args:
        user: cimseller
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: img-cimseller
    container_name: cimseller_container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cimseller

  db:
    image: mysql:5.7.37
    container_name: db-cimseller
    ports:
      - 3300:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - cimseller

  nginx:
    image: nginx:alpine
    container_name: cimseller-nginx
    restart: unless-stopped
    ports:
      - 8111:80
    volumes:
      - ./:/var/www
      - ./Docker/nginx:/etc/nginx/conf.d/
    networks:
      - cimseller

networks:
  cimseller:
    driver: bridge
